### ISSUE TITLE
Calendar layout

### ISSUE THREAD

**Issue by nerijus** [poroussel/simpleagenda#1]
Now calendar is displayed weekdays at the top (i.e. Monday is first column, Tuesday is 2nd column and so on). I would like weekdays to be on the left, i.e. Monday would be first row, Tuesday - 2nd row and so on. Is it possible to add another layout, switchable in the Preferences?

**Comment by nerijus** [comment]
I created a pull request, but it should not be merged as is, because there should be a preference.

**Comment by poroussel** [comment]
Hi Nerijus,

Thanks for your idea and pull request. If you don't beat me to it I'll try to merge your changes with some added preferences.

**Comment by nerijus** [comment]
I've just added a hackish pref to choose weekdays on top or left. Could you please add a gui preference for it instead of my if (WEEKDAYSTOP)?

**Comment by poroussel** [comment]
Resolved by #7 , UI for the settings can be added later
