### ISSUE TITLE
Fix the build against gnustep-gui-0.30.0

### ISSUE THREAD

**Issue by danfe** [poroussel/simpleagenda#12]
In version 0.30.0 update, they've added `APPKIT_EXPORT_CLASS` to support compilation with MSVC, and this change breaks the build.  The following small patch fixes it:
```diff
--- SoundBackend.m.orig
+++ SoundBackend.m
@@ -1,3 +1,4 @@
+#import <AppKit/AppKitDefines.h>
 #import <AppKit/NSSound.h>
 #import "AlarmBackend.h"
 #import "Alarm.h"
```

**Comment by poroussel** [comment]
Thank you for this patch. I just verified it builds without issue on linux as I have no way to test with MSVC.

Edit : and I used something far from real english language in the commit message, sorry about that...

**Comment by danfe** [comment]
>  I just verified it builds without issue on linux as I have no way to test with MSVC.

Oh, it was actually supposed to fix the build on Unix-like systems (e.g. FreeBSD in my case, but I presume GNU/Linux was also affected), the MSVC part is merely a quote from their changelog.

_P.S. On a slightly unrelated note, are there plans for new release?_

**Comment by poroussel** [comment]
Hey, if it builds it's fine with me.

I haven't worked on simpleagenda for years so I'm not sure a release is in order, there's nothing to release. Feel free to prove me wrong !
