### ISSUE TITLE
CalDAV/Nextcloud

### ISSUE THREAD

**Issue by Letterus** [poroussel/simpleagenda#4]
I had no luck with creating a GroupDAV/CalDAV resource that connects to a Nextcloud instance (no reaction, no error message). Should it? Could you provide any hints on how to do it?

Thank you
Johannes

**Comment by poroussel** [comment]
Hi Johannes.

Do you mean that you can create the agenda but that no data appears or that you can't close the agenda creation window ?

What king of URL do you use ?

Can you launch the application from the command line and send me the output ?

**Comment by Letterus** [comment]
If I insert the Calendar/CalDAV URL for a GroupDAV agenda and check dirs it says:

`2021-02-18 11:52:38.410 SimpleAgenda[45217:45217] -[WebDAVResource requestWithMethod:body:attributes:] PROPFIND : 401 Unauthorized`

Which is probably ok, because I do not have a way to provide user credentials?

**Comment by poroussel** [comment]
You should be able to use something like : https://user@password:the.server.com/

**Comment by nerijus** [comment]
Better  https://user:password@the.server.com/ :)

**Comment by poroussel** [comment]
Yes, thanks !

**Comment by Letterus** [comment]
Ok, thank you. So I tried "Check directories" using the following paths:

1. https://user:password@domain.de/remote.php/dav/calendars/username/calendar-uuid/ - Result: Sometimes no error in terminal, sometimes something like `Throwing 0x29a82f8, in flight exception: 0x2e116a8
Exception caught by C++: 0`. Drop down menus for paths get blank (no content), can't "Create". Same if I leave out the UUID. 
2. If I use https://user:password@domain.de/remote.php/dav/calendars/ (without) username - Result: `2021-02-18 14:00:35.541 SimpleAgenda[47931:47931] -[WebDAVResource requestWithMethod:body:attributes:] PROPFIND : 405 Method Not Allowed`

Nextcloud also povides URLs like:

- https://domain.de/remote.php/dav
- https://domain.de/remote.php/dav/principals/users/username/

But neither seems to work. Any hints?

**Comment by poroussel** [comment]
Sorry not hint right now, it's been a while since I used my own software... If you're not in a hurry I might try it when I find some spare time.

**Comment by Letterus** [comment]
Very well. Thank you for your quick response nonetheless. If you want to get started quickly again you may use a Manjaro (VM) installation and my packages prepared over here: https://gnustep.app/

If you like I'd also provide a API key to you so that code pushes will initiate a new package build of your app. Thanks in advance!

**Comment by poroussel** [comment]
I haven't heard about your web site  and packaging effort until now, great work !
I'll get back to this issue when I have a working SimpleAgenda.

**Comment by poroussel** [comment]
Hi Johannes,

I now have a working GNUstep setup but struggle to find a way to test CalDAV. I don't suppose you have an test account on domain.de you could share the credentials ? I would create an account but couldn't find an english version of the website, if you have a link it could also work.

**Comment by Letterus** [comment]
No problem. Sending you credentials via mail in a minute.

**Comment by poroussel** [comment]
Have you successfully used your calendar through caldav from another software ? I just tried with cadaver (command line webdav client) and the connection seems to be dead for a long time before I'm asked to authenticate, this is really strange. Once authenticated I can list the existing files (and I see 2 ics files corresponding to the appointments I created with the web interface) but it's really slow.
I'm not sure this is what makes it unusable with SimpleAgenda but it probably doesn't help.

**Comment by poroussel** [comment]
Answering to myself : disabling IPv6 fixes the delay problem...

**Comment by poroussel** [comment]
Good news, I got it working. I'll have to polish this and make a release, it could take a few days.

**Comment by Letterus** [comment]
Great. Thank you. About IPv6: Yes, there is an issue I have to fix. Great you could work around it.

**Comment by iamleeg** [comment]
We just tested this, if you go to https://user:pass@host/remote.php/dav/calendars/user then SimpleAgenda will correctly find the calendars, and import events. N remaining issues:

 1. it'd be great to have a real UI for gaining the credentials, and somewhere safe to store them
 2. SimpleAgenda should implement discovery via the endpoint Nextcloud offers, which is a proxy location.
 3. Error 415: Unsupported media type trying to PUT an event to the calendar from SimpleAgenda. This is because nextcloud only accepts iCalendar v2.0 and SimpleAgenda emits v1.0.
 4. ~Update works, but timezone differences between server and client aren't being respected (I haven't looked into whether this is SimpleAgenda or Nextcloud or both's fault yet) and updating e.g. the title of an event changes its time.~ No, this is a non bug, I didn't have my timezone configured locally.

**Comment by poroussel** [comment]
After merging #6 I am able to create and modify events on NextCloud backend. My test account is very slow but I think it's a server configuration problem.

Please test latest git and report any issue.

UI changes should be in another issue.

**Comment by poroussel** [comment]
Gone too fast : handling point 2 (proxy location) would be great. Any taker ?!

**Comment by iamleeg** [comment]
We took a look at understanding that issue today, and hope to put up a PR soon.

**Comment by poroussel** [comment]
Great, thanks a lot for your work
